#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cargo
# autospec version: v10
# autospec commit: 6fa3d52
#
Name     : ripgrep
Version  : 14.1.0
Release  : 6
URL      : https://github.com/BurntSushi/ripgrep/archive/14.1.0/ripgrep-14.1.0.tar.gz
Source0  : https://github.com/BurntSushi/ripgrep/archive/14.1.0/ripgrep-14.1.0.tar.gz
Source1  : http://localhost/cgit/vendor/ripgrep/snapshot/ripgrep-2024-01-09-22-23-02.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0 ICU MIT Unicode-DFS-2016 Unlicense
Requires: ripgrep-bin = %{version}-%{release}
Requires: ripgrep-license = %{version}-%{release}
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This directory contains updated benchmarks as of 2018-01-08. They were captured
via the benchsuite script at `benchsuite/benchsuite` from the root of this
repository. The command that was run:

%package bin
Summary: bin components for the ripgrep package.
Group: Binaries
Requires: ripgrep-license = %{version}-%{release}

%description bin
bin components for the ripgrep package.


%package license
Summary: license components for the ripgrep package.
Group: Default

%description license
license components for the ripgrep package.


%prep
%setup -q -n ripgrep-14.1.0
cd %{_builddir}
tar xf %{_sourcedir}/ripgrep-2024-01-09-22-23-02.tar.gz
cd %{_builddir}/ripgrep-14.1.0
mkdir -p ./vendor
cp -r %{_builddir}/ripgrep-2024-01-09-22-23-02/* %{_builddir}/ripgrep-14.1.0/./vendor
mkdir -p .cargo
echo '[source.crates-io]' >> .cargo/config.toml
echo 'replace-with = "vendored-sources"' >> .cargo/config.toml
echo '[source.vendored-sources]' >> .cargo/config.toml
echo 'directory = "vendor"' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cargo build --release

%install
mkdir -p %{buildroot}/usr/share/package-licenses/ripgrep
cp %{_builddir}/ripgrep-%{version}/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/ripgrep-%{version}/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-%{version}/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-%{version}/crates/cli/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-%{version}/crates/cli/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-%{version}/crates/globset/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/ripgrep-%{version}/crates/globset/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-%{version}/crates/globset/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-%{version}/crates/grep/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/ripgrep-%{version}/crates/grep/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-%{version}/crates/grep/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-%{version}/crates/ignore/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/ripgrep-%{version}/crates/ignore/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-%{version}/crates/ignore/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-%{version}/crates/matcher/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-%{version}/crates/matcher/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-%{version}/crates/pcre2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-%{version}/crates/pcre2/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-%{version}/crates/printer/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-%{version}/crates/printer/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-%{version}/crates/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-%{version}/crates/regex/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-%{version}/crates/searcher/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-%{version}/crates/searcher/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/anyhow/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/anyhow/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/bstr/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/bstr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/99b5dc64e06bf0354ef3baac0ea25c929e4e3a9a || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/bstr/src/unicode/data/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/ripgrep/c4f8de16c29dc84a94d610b716fb1c9c7f143582 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/cc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/cc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/crossbeam-channel/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/crossbeam-channel/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/crossbeam-deque/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/crossbeam-deque/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/crossbeam-epoch/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/crossbeam-epoch/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/crossbeam-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/crossbeam-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/encoding_rs/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/encoding_rs/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/b4872d72eb3ccfa74730cc229184eec04f303e7d || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/encoding_rs/LICENSE-WHATWG %{buildroot}/usr/share/package-licenses/ripgrep/1e35cd39af07e5460de3011d5ef8f6a775ee54ae || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/encoding_rs_io/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/93e25f7a8d77fb5a09acece508d3651054a1b123 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/encoding_rs_io/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/encoding_rs_io/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/glob/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/glob/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/jemalloc-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/jemalloc-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/jemalloc-sys/jemalloc/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/c797cef3f1b13a960a5119a084fb88529a924fd7 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/jemallocator/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/jemallocator/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/jobserver/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/aca374a3362a76702c50bd4e7d590a57f8834fc7 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/jobserver/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/ca433b1c16ef9062bcadac922ab3fd859c0b6381 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/lexopt/LICENSE %{buildroot}/usr/share/package-licenses/ripgrep/776c65f4938511a9567be304275bf8f8998ed84d || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/libm/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/libm/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/744183c4ca46703f4b738aca20e238e11c9a3b12 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/memchr/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/memmap2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/c1f96d6a54446beefad79ef49b3c123c597b7a40 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/memmap2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/d5c0c6beed5e77d571189516c53cf05f1e58d9ca || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/packed_simd/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/packed_simd/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/pcre2-sys/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/pcre2-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/pcre2-sys/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/pcre2/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/pcre2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/pcre2/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/pkg-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/pkg-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/regex-automata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/ripgrep/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/ripgrep/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/same-file/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/same-file/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/same-file/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/termcolor/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/termcolor/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/termcolor/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/textwrap/LICENSE %{buildroot}/usr/share/package-licenses/ripgrep/70e36c2f54755e87728778c41ab4b809e5b0b502 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/ripgrep/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/walkdir/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/walkdir/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/walkdir/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/winapi-util/COPYING %{buildroot}/usr/share/package-licenses/ripgrep/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/winapi-util/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/winapi-util/UNLICENSE %{buildroot}/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/winapi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/ripgrep/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/ripgrep-2024-01-09-22-23-02/winapi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/ripgrep/2243f7a86daaa727d34d92e987a741036f288464 || :
cargo install --path . && mkdir -p %{buildroot}/usr/bin && pushd "${HOME}/.cargo/bin/" && mv * %{buildroot}/usr/bin/ && popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ripgrep/144111aa0f14ef5a181326683aa9ebbd9252bca6
/usr/share/package-licenses/ripgrep/1e35cd39af07e5460de3011d5ef8f6a775ee54ae
/usr/share/package-licenses/ripgrep/2243f7a86daaa727d34d92e987a741036f288464
/usr/share/package-licenses/ripgrep/2ad1215c12bd0a3492399dc438aa63084323c662
/usr/share/package-licenses/ripgrep/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/ripgrep/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/ripgrep/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/ripgrep/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/ripgrep/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/ripgrep/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/ripgrep/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/ripgrep/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/ripgrep/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/ripgrep/70e36c2f54755e87728778c41ab4b809e5b0b502
/usr/share/package-licenses/ripgrep/744183c4ca46703f4b738aca20e238e11c9a3b12
/usr/share/package-licenses/ripgrep/776c65f4938511a9567be304275bf8f8998ed84d
/usr/share/package-licenses/ripgrep/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/ripgrep/93e25f7a8d77fb5a09acece508d3651054a1b123
/usr/share/package-licenses/ripgrep/99b5dc64e06bf0354ef3baac0ea25c929e4e3a9a
/usr/share/package-licenses/ripgrep/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/ripgrep/aca374a3362a76702c50bd4e7d590a57f8834fc7
/usr/share/package-licenses/ripgrep/b4872d72eb3ccfa74730cc229184eec04f303e7d
/usr/share/package-licenses/ripgrep/c1f96d6a54446beefad79ef49b3c123c597b7a40
/usr/share/package-licenses/ripgrep/c4f8de16c29dc84a94d610b716fb1c9c7f143582
/usr/share/package-licenses/ripgrep/c797cef3f1b13a960a5119a084fb88529a924fd7
/usr/share/package-licenses/ripgrep/ca433b1c16ef9062bcadac922ab3fd859c0b6381
/usr/share/package-licenses/ripgrep/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/ripgrep/d5c0c6beed5e77d571189516c53cf05f1e58d9ca
/usr/share/package-licenses/ripgrep/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/ripgrep/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/ripgrep/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
